### ISSUE TITLE
Installation fails due to "Invalid Host Name"

### ISSUE THREAD

**Issue by IAmEchino** [mk-pmb/mcaselector-ubuntu-easy-pmb#1]
This is after a few tries, so the entire log isn't here, but you can see the error message I got at the end.

![image](https://user-images.githubusercontent.com/64720141/176342260-a7af60ab-35da-48f2-a6c1-a4a66330b2ab.png)

**Comment by mk-pmb** [comment]
Oh. I see. Seems I messed up the upload. I fixed the repo to have the real 0.1.0 now. Please remove your local copy and clone again freshly.

**Comment by mk-pmb** [comment]
Have you had an opportunity to try it? With no feedback, I'll assume it's fixed and will close the issue in a week or so.

**Comment by IAmEchino** [comment]
> Have you had an opportunity to try it? With no feedback, I'll assume it's fixed and will close the issue in a week or so.

Yes, just did. It works now. Thank you very much for the fix, and I am super thankful that you made this program! It was completely impossible to use MCA Selector with Wine, and I had no idea how to install MCA Selector otherwise due to the whole JavaFX thing. You fixed all of that though, so thank you again!
