### ISSUE TITLE
Installation Failed, "403 Forbidden"

### ISSUE THREAD

**Issue by PaintballGirl77** [mk-pmb/mcaselector-ubuntu-easy-pmb#2]
./easy.sh download failed because of error 403
[
![failed](https://user-images.githubusercontent.com/22944902/177059996-e437d6f7-280e-4cd7-bb4a-35a5d05bf974.png)
](url)

**Comment by mk-pmb** [comment]
This is a decision made by the admins of the JFX download servers. I'm sorry to learn that they seem to not like you. If you know other websites that offer OpenJFX for download, I can consider adding them as a fallback.

**Comment by mk-pmb** [comment]
Fortunately, the file is available on the Wayback Machine. I added their download URL. Please pull and retry.

**Comment by mk-pmb** [comment]
Closing for lack of feedback after fixing. If anyone is still affected, feel free to re-open.
