### ISSUE TITLE
Error 404: Not found on ./easy.sh download

### ISSUE THREAD

**Issue by sbrl** [mk-pmb/mcaselector-ubuntu-easy-pmb#3]
When using this script, I get the following error:

```
$ ./easy.sh 
D: Found Java major version: 21
D: Using mcaselector-2.4.1.jar
E: Not a directory: 'javafx-sdk-21/lib'. Try run: ./easy.sh download
sbrl@Starfall:/tmp/x/mcaselector-ubuntu-easy-pmb$ ./easy.sh download
D: Found Java major version: 21
D: Gonna download JavaFX (official download servers): javafx-21-ea-sdk-linux.zip <- accept-bad-cert:https://gluonhq.com/download/javafx-21-ea-sdk-linux/.zip

--2024-08-18 20:06:07--  https://gluonhq.com/download/javafx-21-ea-sdk-linux/.zip
Resolving gluonhq.com (gluonhq.com)... 45.55.56.81
Connecting to gluonhq.com (gluonhq.com)|45.55.56.81|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-08-18 20:06:08 ERROR 404: Not Found.

E: wget failed, rv=8
W: Download from official servers failed. Trying inofficial mirrors.
D: Gonna download JavaFX (via archive.org): javafx-21-ea-sdk-linux.zip <- https://web.archive.org/web/99/https://gluonhq.com/download/javafx-21-ea-sdk-linux/

--2024-08-18 20:06:08--  https://web.archive.org/web/99/https://gluonhq.com/download/javafx-21-ea-sdk-linux/
Resolving web.archive.org (web.archive.org)... 207.241.237.3
Connecting to web.archive.org (web.archive.org)|207.241.237.3|:443... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2024-08-18 20:06:10 ERROR 404: NOT FOUND.

E: wget failed, rv=8
E: Downloads failed from all known mirrors.
```

....with mcaselector downloaded from the latest release.

**Comment by mk-pmb** [comment]
Thanks for the report! I'll try and find the new URL. Meanwhile, try using Java 17 for MCA. It should be possible to have that and 21 installed at the same time.

Edit: Progress update: I've made the error message more helpful.

**Comment by mk-pmb** [comment]
Updating to v21 turned out more complicated than expected, so for now I resort to only supporting v17. I've adjusted the readme accordingly.

**Comment by sbrl** [comment]
Ah okay. I don't know whether there's a package in the Ubuntu repos for Java 17 or not, so I'll have to check.

**Comment by mk-pmb** [comment]
`openjdk-17-jdk` was/is [available in focal](https://packages.ubuntu.com/focal/openjdk-17-jdk) and is still [available in oracular](https://packages.ubuntu.com/oracular/openjdk-17-jdk). JavaFX 17 [has support "until September 2026"](https://web.archive.org/web/20240819040702/https://gluonhq.com/products/javafx/) so I guess Java 17 will be supported for at least that long.
